export const UserRoles ={
	HELPER_USER:"HELPER_USER",
	NORMAL_USER:"NORMAL_USER"
};

export const helpGigStatus = {
	ACTIVE:"ACTIVE",
	CANCELLED:"CANCELLED",
	ASSIGNED:"ASSIGNED",
	TIMEOUT:"TIMEOUT",
	REQUESTED_TO_ASSIGN:"REQUESTED_TO_ASSIGN",
};

export const helperStatus = {
	AVAILABLE:"AVAILABLE",
	NOT_AVAILABLE: "NOT_AVAILABLE",
};