export const GetHelp = {
	INSERTING_HELP:"INSERTING_HELP",
	HELP_INSERTED :"HELP_INSERTED",
	CANCEL_HELP :"CANCEL_HELP",
	UPDATE_HELP_GIG:"UPDATE_HELP_GIG",
	INSERT_ACCEPTED_GIG:'INSERT_ACCEPTED_GIG'
};
