const Users = {
	GET_USER_DATA:"GET_USER_DATA",
	SET_NEW_USER_DATA: "SET_NEW_USER_DATA",
	INSERT_USER_DETAILS:"INSERT_USER_DETAILS",
	UPDATE_DETAILS: "UPDATE_DETAILS",
	UPDATING_PROFILE_DETAILS:"UPDATING_PROFILE_DETAILS",
	UPDATING_MEETING_LINK:"UPDATING_MEETING_LINK",
	UPDATE_MEETING_LINK:"UPDATE_MEETING_LINK",
	GET_HELP_GIG_DATA: "GET_HELP_GIG_DATA",
	UPDATE_HELPER_USER_STATUS:"UPDATE_HELPER_USER_STATUS",
	GET_HELPER_USER_DATA: "GET_HELPER_USER_DATA"
};
export default Users;
