const Users = {
	GET_USER_DATA:"GET_USER_DATA",
	SET_NEW_USER_DATA: "SET_NEW_USER_DATA",
	INSERT_USER_DETAILS:"INSERT_USER_DETAILS",
	UPDATE_SUBJECTS: "UPDATE_SUBJECTS",
	UPDATING_SUBJECTS:"UPDATING_SUBJECTS",
	UPDATING_MEETING_LINK:"UPDATING_MEETING_LINK",
	UPDATE_MEETING_LINK:"UPDATE_MEETING_LINK"
};
export default Users;
